pipeline{
  agent any
  stages {
    stage('checkout'){
      steps{
        git url: 'https://github.com/Jagadishvvsr/mega-prod-java.git', branch: 'main'
      }
    }

    stage('clean'){
      steps{
        sh 'echo "cleaning the workspace for new build"'
        sh 'mvn clean'
      }
    }

    stage('compile'){
      steps{
        sh 'echo "building..."'
        sh 'mvn compile'
      }
    }

    stage('test'){
      steps{
        sh 'mvn test'
      }
      post{
        always{
          junit '**/target/surefire-reports/*.xml'
        }
      }
    }

    stage('package'){
      steps{
        sh 'mvn -DskipTests package'
      }
    }

    stage('integration test and code coverage'){
      steps{
        // run ITs only (don’t re-run unit tests)
        sh 'mvn verify'
        // pick up JaCoCo exec files generated by Maven
        jacoco execPattern: '**/jacoco*.exec'
      }
      post{
        always{
          junit allowEmptyResults: true, testResults: '**/target/failsafe-reports/*.xml'
          junit allowEmptyResults: true, testResults: '**/target/surefire-reports/*.xml'
          archiveArtifacts artifacts: '**/target/site/jacoco/**, **/target/*.exec', allowEmptyArchive: true
        }
      }
    }
  }

  post{
    success{
      archiveArtifacts artifacts: 'target/*.jar', allowEmptyArchive: true
    }
  }
}
