app:
  storage:
    s3:
      enabled: true
      bucket: ${S3_BUCKET}
      region: ${AWS_REGION:us-east-1}
# Credentials are taken from the default provider chain:
# - Environment: AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY
# - Profile: ~/.aws/credentials
# - EC2/ECS IAM Role
